version: '3'

services:
  codeigniter-starter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: codeigniter-starter
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
